version: '3.8'

services:
  server:
    build:
      context: ./database_service
      dockerfile: Dockerfile
    container_name: iot1_server
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  client:
    build:
      context: ./rest_service
      dockerfile: Dockerfile
    container_name: iot1_client
    environment:
      - PYTHONPATH=.
    ports:
      - "8000:8000"
    depends_on:
      - server
    networks:
      - app-network
      
  db:
    image: mongo:latest
    container_name: iot1_db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge