services:
  server:
    build:
      context: ./database_service
      dockerfile: ./database_service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  client:
    build:
      context: ./rest_service
      dockerfile: ./rest_service/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - server
      
  db:
    image: mongo:latest
    ports:
      - "27017:27017"